# TC/test_fastapi_cicd.yaml
# 이 파일은 FastAPI 프로젝트의 CI/CD 파이프라인을 정의하는 GitHub Actions 워크플로우입니다.
# 명세서의 각 테스트 케이스(TC)가 파이프라인의 어떤 단계에서 검증되는지 주석으로 표기했습니다.

name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 전역 환경변수 설정
env:
  DOCKER_IMAGE: your-docker-hub-username/your-fastapi-app # Docker Hub 사용자명/이미지명으로 변경
  FASTAPI_PROJECT_PATH: ./ETL/api # FastAPI 프로젝트 경로

jobs:
  # =================================================================
  #  1. 테스트 및 코드 품질 검사 (Test & Lint)
  # =================================================================
  test-and-lint:
    name: Test, Lint, and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up uv (Python environment)
        uses: astral-sh/setup-uv@v1

      - name: 3. Install dependencies with uv sync
        # TC_002: 의존성 누락 시 --strict 옵션으로 인해 이 단계에서 파이프라인이 실패합니다.
        working-directory: ${{ env.FASTAPI_PROJECT_PATH }}
        run: uv sync --strict

      - name: 4. Lint with Ruff (or Black/Flake8)
        # TC_007: 코드 스타일이 규칙에 맞지 않으면 이 단계에서 파이프라인이 실패합니다.
        working-directory: ${{ env.FASTAPI_PROJECT_PATH }}
        run: uv run ruff check . --exit-non-zero-on-fix

      - name: 5. Run tests with pytest and generate coverage report
        # 파이프라인 성공의 일부 (TC_001)
        working-directory: ${{ env.FASTAPI_PROJECT_PATH }}
        run: uv run pytest --cov=. --cov-report=xml

      - name: 6. Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ env.FASTAPI_PROJECT_PATH }}/coverage.xml

  # =================================================================
  #  2. Docker 이미지 빌드 및 보안 스캔 (Build & Scan)
  # =================================================================
  build-and-scan:
    name: Build, Push, and Scan Docker Image
    needs: test-and-lint # 'test-and-lint' 작업이 성공해야 실행
    if: github.ref == 'refs/heads/main' # 'main' 브랜치에 push될 때만 실행
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 4. Verify Secret Masking
        # TC_008: GitHub Actions가 자동으로 시크릿을 '***'로 마스킹하는지 확인하는 단계
        # 이 단계의 로그에는 실제 시크릿 값이 아닌 마스킹된 값이 출력됩니다.
        run: echo "Secret token starts with: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"

      - name: 5. Build and push Docker image
        # 파이프라인 성공의 일부 (TC_001)
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FASTAPI_PROJECT_PATH }}
          file: ${{ env.FASTAPI_PROJECT_PATH }}/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 6. Scan image with Trivy
        # TC_009: 빌드된 이미지의 보안 취약점을 스캔하고, High/Critical 등급 발견 시 파이프라인을 실패시킴
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          format: 'table'
          exit-code: '1' # High, Critical 취약점 발견 시 1을 반환하여 빌드 실패
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  # =================================================================
  #  3. 프로덕션 환경에 배포 (Deploy)
  # =================================================================
  deploy:
    name: Deploy to Production and Verify
    needs: build-and-scan # 'build-and-scan' 작업이 성공해야 실행
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production # GitHub 환경 설정 (필요시)

    steps:
      - name: 1. Deploy to server
        # 이 단계는 실제 배포 환경에 따라 달라집니다. (예: SSH, kubectl, AWS CodeDeploy 등)
        # 예시: SSH를 통해 서버에 접속하여 docker-compose로 새 이미지를 실행
        run: |
          echo "Deploying image ${{ env.DOCKER_IMAGE }}:${{ github.sha }}"...
          # ssh user@your-server "
          #   cd /path/to/app && \
          #   export DOCKER_IMAGE_TAG=${{ github.sha }} && \
          #   docker-compose pull && \
          #   docker-compose up -d --no-deps your-fastapi-service
          # "
          echo "Deployment initiated."

      - name: 2. Health Check
        # TC_010: 배포된 서비스가 정상적으로 응답할 때까지 최대 1분간 5초 간격으로 상태 확인
        # 최종적으로 파이프라인 성공을 결정짓는 단계 (TC_001)
        run: |
          echo "Starting health check..."
          END_TIME=$(( $(date +%s) + 60 ))
          while [ $(date +%s) -lt $END_TIME ]; do
            STATUS_CODE=$(curl -s -o /dev/null -w "%http_code")
            if [ $STATUS_CODE -eq 200 ]; then
              echo "Health check PASSED with status 200."
              exit 0
            fi
            echo "Health check failed with status $STATUS_CODE. Retrying in 5 seconds..."
            sleep 5
          done
          echo "Health check FAILED after 60 seconds."
          exit 1
